# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyplayer/interfaces/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 40, 16, 16))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(220, 280, 381, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.time_bar = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.time_bar.setOrientation(QtCore.Qt.Horizontal)
        self.time_bar.setObjectName("time_bar")
        self.gridLayout.addWidget(self.time_bar, 0, 0, 1, 2)
        self.play_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.play_button.setObjectName("play_button")
        self.gridLayout.addWidget(self.play_button, 1, 1, 1, 1)
        self.pause_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pause_button.setObjectName("pause_button")
        self.gridLayout.addWidget(self.pause_button, 1, 0, 1, 1)
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(370, 250, 71, 27))
        self.time_label.setObjectName("time_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        self.time_label.setText(_translate("MainWindow", "TextLabel"))
