# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyplayer/interfaces/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 323, 301, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.songname_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.songname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.songname_label.setObjectName("songname_label")
        self.verticalLayout_3.addWidget(self.songname_label)
        self.time_bar = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.time_bar.setOrientation(QtCore.Qt.Horizontal)
        self.time_bar.setObjectName("time_bar")
        self.verticalLayout_3.addWidget(self.time_bar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.artistname_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.artistname_label.setObjectName("artistname_label")
        self.horizontalLayout_2.addWidget(self.artistname_label)
        self.currenttime_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currenttime_label.setObjectName("currenttime_label")
        self.horizontalLayout_2.addWidget(self.currenttime_label)
        self.songduration_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.songduration_label.setObjectName("songduration_label")
        self.horizontalLayout_2.addWidget(self.songduration_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.play_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.play_button.setObjectName("play_button")
        self.horizontalLayout.addWidget(self.play_button)
        self.pause_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout.addWidget(self.pause_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.songpicture_label = QtWidgets.QLabel(self.centralwidget)
        self.songpicture_label.setGeometry(QtCore.QRect(360, 190, 151, 131))
        self.songpicture_label.setObjectName("songpicture_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.songname_label.setText(_translate("MainWindow", "Songname"))
        self.artistname_label.setText(_translate("MainWindow", "Artist"))
        self.currenttime_label.setText(_translate("MainWindow", "Current time"))
        self.songduration_label.setText(_translate("MainWindow", "Song duration"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        self.songpicture_label.setText(_translate("MainWindow", "TextLabel"))
